### ISSUE TITLE
Create activity to show the results

### ISSUE THREAD

**Issue by pevad95** [FalsyQuiz/FalsyQuiz#30]
[https://developer.android.com/guide/topics/ui/layout/grid.html](https://developer.android.com/guide/topics/ui/layout/grid.html)
- Results should appear in a table
- Show every info from Game object
- go back to Main menu with back button
- extends AbstractActivity

**Comment by viktoriagecse** [comment]
It has been implemented by @pevad95 (issue number is 44: https://github.com/FalsyQuiz/FalsyQuiz/issues/44 )
